// Generated by CoffeeScript 1.6.2
/*
Author: bmsantiago
*/


(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    placeholder: function(options) {
      var _defaults;

      _defaults = {
        "fontColor": "#999",
        "class": "",
        "styles": ""
      };
      options = $.extend(_defaults, options);
      if (!('placeholder' in document.createElement('input'))) {
        return $(this).each(function(index) {
          var $cur_input, $span, placeholder, spanCSS;

          $cur_input = $(this);
          placeholder = $cur_input.attr('placeholder');
          if ((placeholder != null)) {
            if ($cur_input.css("margin") === "auto") {
              $cur_input.css("margin", "0");
            }
            spanCSS = {
              "font-size": $cur_input.css('font-size'),
              "bottom": $cur_input.height() + (parseInt($cur_input.css('padding-bottom').replace("px", "")) * 2) + 2,
              "margin": $cur_input.css('margin'),
              "margin-bottom": (($cur_input.height() * 2) + 7) * -1,
              "font-family": $cur_input.css('font-family'),
              "padding": $cur_input.css('padding'),
              "padding-left": parseInt($cur_input.css('padding-left').replace("px", "")) + 2,
              "width": $cur_input.width(),
              "height": $cur_input.height(),
              "color": options.fontColor,
              "position": "relative"
            };
            $span = $('<span></span>').hide();
            $span.css(spanCSS);
            $span.css(options.styles);
            $span.html(placeholder);
            $span.addClass(options["class"]);
            $span.insertAfter($cur_input);
            if ($cur_input.val() === "") {
              $span.css('display', 'block');
            }
            $span.on("click", function() {
              var $input;

              $(this).hide();
              $input = $(this).prev();
              return $input.focus();
            });
            $cur_input.on("focus", function() {
              return $(this).next().hide();
            });
            return $cur_input.on('focusout', function() {
              if ($(this).val() === "") {
                return $(this).next().show();
              }
            });
          }
        });
      }
    }
  });

}).call(this);
